<?php
$form->setAttribute('action', $this->url('User', ['action' => 'add']));
$form->prepare();

// echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
// echo $this->formRow($form->get('title'));
// echo $this->formRow($form->get('artist'));
// echo $this->formSubmit($form->get('submit'));
// echo $this->form()->closeTag();
$this->headLink()->prependStylesheet($this->basePath('css/aurora.css'));
// This provides a default CSS class and placeholder text for the title element:
$User = $form->get('title');
$User->setAttribute('class', 'form-control');
$User->setAttribute('placeholder', 'User title');
//$User->setAttribute('size', '100');
$User->setAttribute('maxlength', '100');

// This provides a default CSS class and placeholder text for the artist element:
$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');
$artist->setAttribute('maxlength', '100');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

// $form->setAttribute('action', $this->url('User', ['action' => 'add']));
// $form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($User) ?>
    <?= $this->formElement($User) ?>
    <?= $this->formElementErrors()->render($User, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
