<?php
// module/User/view/User/User/index.phtml:

$title = 'My Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <span>Add new User</span>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($Users as $User) : ?>
    <tr>
        <td><?= $this->escapeHtml($User->title) ?></td>
        <td><?= $this->escapeHtml($User->artist) ?></td>
        <td>
            <a href="<?= $this->url('User', ['action' => 'edit', 'id' => $User->id]) ?>">Edit</a>
            <a href="<?= $this->url('User', ['action' => 'delete', 'id' => $User->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
<?php echo $this->form_template; ?>
</table>