<?php 
$this->headLink()->prependStylesheet($this->basePath('css/aurora.css'));
$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$User = $form->get('title');
$User->setAttribute('class', 'form-control');
$User->setAttribute('placeholder', 'User title');
$User->setAttribute('maxlength', '100');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');
$artist->setAttribute('maxlength', '100');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('User', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($User) ?>
    <?= $this->formElement($User) ?>
    <?= $this->formElementErrors()->render($User, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($artist) ?>
    <?= $this->formElement($artist) ?>
    <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();