<?php
/**
 * @var $this \Laminas\View\Renderer\PhpRenderer|\Laminas\Form\View\HelperTrait 
 */
//$this->
$this->headLink()->prependStylesheet($this->basePath('css/aurora.css'));
$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$name = $form->get('userName');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'User title');
$name->setAttribute('maxlength', '100');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');
$email->setAttribute('maxlength', '100');

$role = $form->get('role');
$role->setAttribute('class', 'form-control');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('user', [
    'action' => 'edit',
    'userName'     => $userName,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>
<?php
//var_dump($this->acl);
if($acl->isAllowed($this->user, $this->user, 'admin.user')):
?>
<div class="form-group">
	<?= $this->formLabel($role); ?>
	<?= $this->formElement($role); ?>
	<?= $this->formElementErrors()->render($role, ['class' => 'help-block']) ?>
</div>
<?php
endif;
?>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();