<?php
$title = 'System Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
if($hasMessage) :
?>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
   <?=$this->flashMessenger()->renderCurrent('info'); ?>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<?php
endif;
?>
<p>
	<?php
	if($this->acl->isAllowed($this->user, $this->user, 'user.create.new')):
	?>
    <span><a href="<?= $this->url('user.register', ['action' => 'add', 'id' => 0]) ?>" class="btn btn-outline-info btn-sm">Add User</a></span>
    <?php 
    endif;
    ?>
</p>

<table class="table">
<tr>
	<th>Profile</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Account Status</th>
    <th>Verification Status</th>
    <th>Account Actions</th>
</tr>
<?php
foreach ($users as $listUser) :
?>
    <tr>
    <?php // ?>
    	<td><a href="<?=$this->url('profile', ['action' => 'view', 'userName' => $listUser->userName]); ?>" class="btn btn-outline-info btn-sm">Profile</a></td>
        <td><?= $this->escapeHtml($listUser->userName) ?></td>
        <td><?= $this->escapeHtml($listUser->email) ?></td>
        <?php
        if ((bool) $listUser->active) :
        ?>
			<td>Active</td>
			<?php
            else :
            ?>
			<td>Inactive</td>
		<?php
        endif;
        ?>
		
        <?php
        if ((bool) $listUser->verified) :
        ?>
        	<td>Verified</td>
			<?php
            else :
            ?>
			<td>Not Verified</td>
		<?php
        endif;
        ?>
		<td>
			<?php 
			if($this->acl->isAllowed($this->user, $listUser, 'edit')):
			?>
			<a href="<?=$this->url('user', ['action' => 'edit', 'userName' => $listUser->userName]); ?>" class="btn btn-outline-warning btn-sm">Edit</a>
			<a href="<?=$this->url('user', ['action' => 'delete', 'userName' => $listUser->userName]); ?>" class="btn btn-outline-danger btn-sm">Delete</a>
			<?php 
			endif;
			?>
		</td>
	</tr>
<?php endforeach; ?>
</table>