<?php
// module/User/view/User/User/index.phtml:

$title = 'System Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php 
               //var_dump($this->user);
//                 $this->navigation()->setAcl($this->acl);
//                 $this->navigation()->setRole($this->user->role);
//                 $this->navigation()->menu()->setUlClass('nav nav-tabs');
//                 //$this->navigation()->menu()->setPartial('application/partials/button-menu');
//                 echo $this->navigation('Laminas\Navigation\User')->menu();
                ?>
<p>
	<?php 
	if($this->acl->isAllowed($this->user, $this->user, 'user.create.new')):
	?>
    <span><a href="<?= $this->url('user', ['action' => 'add', 'id' => 0]) ?>">Add User</a></span>
    <?php 
    endif;
    ?>
</p>

<table class="table">
<tr>
	<th>Profile</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Account Status</th>
    <th>Verification Status</th>
    <th>Account Actions</th>
</tr>
<?php foreach ($users as $user) : ?>
    <tr>
    	<td><a href="<?= $this->url('profile', ['action' => 'view', 'id' => $user->id])?>">View</a></td>
        <td><?= $this->escapeHtml($user->userName) ?></td>
        <td><?= $this->escapeHtml($user->email) ?></td>
        <?php
    if ((bool) $user->active) :
        ?>
		<td>Active</td>
		<?php
    else :
        ?>
		<td>Inactive</td>
		<?php
    endif;
    ?>
		
        <?php
    if ((bool) $user->verified) :
        ?>
        
		<td>Verified</td>
		<?php
    else :
        ?>
		<td>Not Verified</td>
		<?php
    endif;
    ?>
		<td>
			<?php 
			if($this->acl->isAllowed($this->user, $user, 'edit')):
			?>
			<a
			href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
			<a
			href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
			<?php 
			endif;
			?>
		</td>
	</tr>
<?php endforeach; ?>

</table>