<?php
use User\Model\User;
// module/User/view/User/User/index.phtml:

$title = 'System Users';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
	<?php 
	//var_dump($this->user);
	if($this->acl->isAllowed($this->user, $this->user, 'user.create.new')):
	?>
    <span><a href="<?= $this->url('user', ['action' => 'add', 'id' => 0]) ?>">Add User</a></span>
    <?php 
    endif;
    ?>
</p>

<table class="table">
<tr>
	<th>Profile</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Account Status</th>
    <th>Verification Status</th>
    <th>Account Actions</th>
</tr>
<?php 
//$userObject = new User([]);
foreach ($users as $user) : 
$user = new User($user);
//var_dump($user);
?>
    <tr>
    	<td><a href="<?= $this->url('profile', ['action' => 'view', 'userName' => $user->userName])?>">View</a></td>
        <td><?= $this->escapeHtml($user->userName) ?></td>
        <td><?= $this->escapeHtml($user->email) ?></td>
        <?php
    if ((bool) $user->active) :
        ?>
		<td>Active</td>
		<?php
    else :
        ?>
		<td>Inactive</td>
		<?php
    endif;
    ?>
		
        <?php
    if ((bool) $user->verified) :
        ?>
        
		<td>Verified</td>
		<?php
    else :
        ?>
		<td>Not Verified</td>
		<?php
    endif;
    ?>
		<td>
			<?php 
			if($this->acl->isAllowed($this->user, $user, 'edit')):
			?>
			<a
			href="<?= $this->url('user', ['action' => 'edit', 'userName' => $user->userName]) ?>">Edit</a>
			<a
			href="<?= $this->url('user', ['action' => 'delete', 'userName' => $user->userName]) ?>">Delete</a>
			<?php 
			endif;
			?>
		</td>
	</tr>
<?php endforeach; ?>

</table>